const path=require('node:path');
const constructors={local:'NewLocal',s3:'NewS3','aliyun-oss':'NewAliyunOSS','tencent-cos':'NewTencentCOS'};
const providerFile={'local':'local.go','s3':'s3.go','aliyun-oss':'aliyun_oss.go','tencent-cos':'tencent_cos.go'};
function buildGoStorage({s,config,owner,selectedProviders,add,readSource,deps,owned}){
  const files=['storage.go','private.go','local.go','cloud.go','extensions.go','live_test.go','repository.go','service.go','http.go','storage_test.go',...selectedProviders.filter(p=>p!=='local').map(p=>providerFile[p])];
  for(const file of files)add(s.path+'/'+file,readSource('architecture/modules/storage/go/'+file),'update',owner);
  for(const p of selectedProviders.filter(p=>p!=='local'))add(s.path+'/'+providerFile[p].replace('.go','_test.go'),readSource('architecture/modules/storage/go/'+providerFile[p].replace('.go','_test.go')),'update',owner);
  const selected=Object.entries(deps.storage.go).filter(([name])=>selectedProviders.includes('s3')&&name.startsWith('github.com/aws/')||selectedProviders.includes('aliyun-oss')&&name.startsWith('github.com/aliyun/')||selectedProviders.includes('tencent-cos')&&name.startsWith('github.com/tencentyun/'));
  add(s.path+'/go.mod','module xirang.local/storage\n\ngo 1.26.0\n'+(selected.length?'\nrequire (\n'+selected.map(([name,v])=>'\t'+name+' '+v).join('\n')+'\n)\n':''),'update',owner);
  const setup=s.stores.map(store=>{const id=JSON.stringify(store.id),prefix=JSON.stringify(store.envPrefix);return store.provider==='local'?'{ directory:=env('+prefix+'+"_DIRECTORY");if directory==""{directory=filepath.Join(dataRoot,"objects",'+id+')};provider,err:=NewLocal(directory);if err!=nil{return nil,err};stores['+id+']=provider }':'{ options,err:=cloudEnvironment('+prefix+',env);if err!=nil{return nil,err};provider,err:='+constructors[store.provider]+'(options);if err!=nil{return nil,err};stores['+id+']=provider }';}).join('\n');
  add(s.path+'/configured.go','package storage\nimport("context";"path/filepath";"time")\n// dataRoot must be a private absolute application data directory. env normally is os.Getenv.\nfunc NewConfiguredStorage(dataRoot string,env func(string)string)(router *Router,err error){if !filepath.IsAbs(dataRoot)||env==nil{return nil,fail("CONFIGURATION")};stores:=map[string]Provider{};defer func(){if err!=nil{for _,p:=range stores{if c,ok:=p.(interface{Close()error});ok{_ =c.Close()}}}}();\n'+setup+'\nreturn NewRouter(stores,'+JSON.stringify(s.defaultStore)+')}\nfunc cloudEnvironment(prefix string,env func(string)string)(CloudOptions,error){options:=CloudOptions{Bucket:env(prefix+"_BUCKET"),Region:env(prefix+"_REGION"),Endpoint:env(prefix+"_ENDPOINT"),PublicEndpoint:env(prefix+"_PUBLIC_ENDPOINT"),ForcePathStyle:env(prefix+"_FORCE_PATH_STYLE")=="true",Credentials:func(context.Context)(Credentials,error){c:=Credentials{AccessKeyID:env(prefix+"_ACCESS_KEY_ID"),SecretAccessKey:env(prefix+"_SECRET_ACCESS_KEY"),SessionToken:env(prefix+"_SESSION_TOKEN")};if c.AccessKeyID==""||c.SecretAccessKey==""{return c,fail("CONFIGURATION")};if raw:=env(prefix+"_CREDENTIAL_EXPIRATION");raw!=""{var err error;c.Expiration,err=time.Parse(time.RFC3339,raw);if err!=nil{return c,fail("CONFIGURATION")}};return c,nil}};return options,options.Validate()}\n','update',owner);
  add(s.path+'/.gitignore','.data/\n.env\n.env.local\n','append-lines',owner);
  add(s.path+'/.env.example',s.stores.map(store=>store.provider==='local'?store.envPrefix+'_DIRECTORY=\n':['BUCKET','REGION','ENDPOINT','PUBLIC_ENDPOINT','ACCESS_KEY_ID','SECRET_ACCESS_KEY','SESSION_TOKEN','CREDENTIAL_EXPIRATION'].map(k=>store.envPrefix+'_'+k+'=').join('\n')+'\n').join('\n'),'init-if-missing',owner);
  for(const app of config.applications.filter(a=>s.consumers.includes(a.id))){add(app.path+'/file_storage.go',readSource('architecture/modules/storage/go-example.go'),'init-if-missing','architecture:app:'+app.id);const asset=owned.get(app.path+'/go.mod');if(asset){asset.content=asset.content.replace(/go \d+\.\d+(?:\.\d+)?/,'go 1.26.0');asset.content+='\nrequire xirang.local/storage v0.0.0\nreplace xirang.local/storage => '+path.posix.relative(app.path,s.path)+'\n';asset.strategy='update';}}
}
module.exports={buildGoStorage};
