import OSS from 'ali-oss';
import {StorageError,call,validKey,validVersionId,ossVersionId,pageLimit} from '../contracts.ts';
import {cloudOptions,signedProvider,signed,expiresIn,fromHeaders} from '../cloud.ts';
import type {VersionedStorageProvider,ListInput,ObjectVersion} from '../contracts.ts';
import type {CloudOptions} from '../cloud.ts';
export function createAliyunOSSProvider(options:CloudOptions){
  const o=cloudOptions(options);
  async function client(publicURL=false){if(!o.credentials)throw new StorageError('CONFIGURATION','OSS credential provider is required');const credentials=await o.credentials();const sdk=new OSS({bucket:o.bucket,region:o.region.startsWith('oss-')?o.region:'oss-'+o.region,endpoint:publicURL?(o.publicEndpoint||o.endpoint):o.endpoint,accessKeyId:credentials.accessKeyId,accessKeySecret:credentials.secretAccessKey,stsToken:credentials.sessionToken,authorizationV4:true,refreshSTSTokenInterval:60000,secure:!o.allowHTTP,timeout:60000});return {sdk,credentials};}
  const provider = signedProvider('aliyun-oss',{
    async sign(method,key,input,publicURL){const {sdk,credentials}=await client(publicURL),seconds=expiresIn(input.expiresIn,credentials),headers:Record<string,string>=method==='PUT'?{'Content-Type':input.contentType!}:{};return signed(method,await sdk.signatureUrlV4(method,seconds,{headers:method==='PUT'?{...headers,'Content-Length':String(input.size)}:headers,queries:method==='GET'?{'response-content-disposition':'attachment'}:undefined},key,method==='PUT'?['content-length']:[]),headers,seconds);},
    async head(key){const {sdk}=await client(),r=await sdk.head(key),h=r.res.headers as Record<string,string>;return {key,size:Number(h['content-length']),contentType:String(h['content-type']||'application/octet-stream'),etag:String(h.etag||''),modifiedAt:String(h['last-modified']||''),versionId:ossVersionId(h['x-oss-version-id'])};},
    async delete(key){const {sdk}=await client();await sdk.delete(key);},
    async list(input={}){const {sdk}=await client();const r=await sdk.listV2({prefix:input.prefix,'continuation-token':input.cursor,'max-keys':input.limit||50},{});return {items:(r.objects||[]).map(v=>({key:v.name,size:Number(v.size),contentType:'application/octet-stream',etag:v.etag,modifiedAt:v.lastModified})),cursor:r.isTruncated?r.nextContinuationToken:undefined};}
  });
  type VersionSDK = {getBucketVersioning(bucket:string):Promise<{versionStatus?:string}>;listObjectVersions(query:Record<string,unknown>):Promise<{objects:{name:string;versionId:string;size:number}[];deleteMarker:{name:string;versionId:string}[];isTruncated:boolean;nextKeyMarker?:string;nextVersionIdMarker?:string}>};
  async function sdkClient(){return (await client()).sdk;}
  async function versionHead(key:string,versionId:string){validKey(key);validVersionId(versionId);const sdk=await sdkClient(),r=await sdk.head(key,{versionId} as OSS.HeadObjectOptions),h=r.res.headers as Record<string,string>;const actual=ossVersionId(h['x-oss-version-id']);if(actual!==versionId)throw new StorageError('CONFLICT','Object version mismatch');return {...fromHeaders(key,new Headers(h)),versionId:actual};}
  return Object.assign(provider,{
    headVersion:(key:string,versionId:string)=>call(()=>versionHead(key,versionId)),
    getVersion:(key:string,versionId:string)=>call(async()=>{validKey(key);validVersionId(versionId);const sdk=await sdkClient(),r=await sdk.getStream(key,{subres:{versionId}} as OSS.GetStreamOptions),h=r.res.headers as Record<string,string>;try{const actual=ossVersionId(h['x-oss-version-id']);if(actual!==versionId)throw new StorageError('CONFLICT','Object version mismatch');const size=Number(h['content-length']);if(!Number.isSafeInteger(size)||size<0)throw new StorageError('UNAVAILABLE');return {body:r.stream,info:{key,size,contentType:String(h['content-type']||'application/octet-stream'),versionId:actual}};}catch(e){r.stream.destroy();throw e;}}),
    deleteVersion:(key:string,versionId:string)=>call(async()=>{validKey(key);validVersionId(versionId);const sdk=await sdkClient();await sdk.delete(key,{versionId} as OSS.RequestOptions);}),
    listVersions:(input:ListInput={})=>call(async()=>{
      const limit=pageLimit(input.limit),prefix=input.prefix||'';if(prefix.length>1024||/[\x00-\x1f\x7f]/.test(prefix))throw new StorageError('INVALID_INPUT');input.signal?.throwIfAborted();
      let cursor:{mode:string;prefix:string;key?:string;version?:string;token?:string}|undefined;
      if(input.cursor){try{if(input.cursor.length>8192)throw 0;cursor=JSON.parse(Buffer.from(input.cursor,'base64url').toString());if(!cursor||cursor.prefix!==prefix||!['','Enabled','Suspended'].includes(cursor.mode)||typeof cursor.key!=='string'||typeof cursor.version!=='string'||typeof cursor.token!=='string'||(!cursor.mode&&!cursor.token))throw 0;if(cursor.mode){validKey(cursor.key);validVersionId(cursor.version);if(!cursor.key.startsWith(prefix))throw 0;}}catch{throw new StorageError('INVALID_INPUT','Invalid version cursor');}}
      const sdk=await sdkClient(),vs=sdk as unknown as VersionSDK,{versionStatus}=await vs.getBucketVersioning(o.bucket),mode=versionStatus===undefined?'':versionStatus;
      if(!['','Enabled','Suspended'].includes(mode))throw new StorageError('UNAVAILABLE','Unknown bucket versioning state');if(cursor&&cursor.mode!==mode)throw new StorageError('CONFLICT','Bucket versioning changed');
      let items:ObjectVersion[],truncated:boolean,key='',version='',token='';
      if(!mode){const r=await sdk.listV2({prefix,'continuation-token':cursor?.token,'max-keys':limit},{});items=(r.objects||[]).map(v=>({key:v.name,size:Number(v.size),contentType:'application/octet-stream',versionId:'null',deleteMarker:false}));truncated=r.isTruncated;token=r.nextContinuationToken||'';}
      else{const r=await vs.listObjectVersions({prefix,maxKeys:limit,...(cursor?{keyMarker:cursor.key,versionIdMarker:cursor.version}:{})});items=[...(r.objects||[]).map(v=>({key:v.name,size:v.size,contentType:'application/octet-stream',versionId:v.versionId,deleteMarker:false})),...(r.deleteMarker||[]).map(v=>({key:v.name,size:0,contentType:'application/octet-stream',versionId:v.versionId,deleteMarker:true}))];truncated=r.isTruncated;key=r.nextKeyMarker||'';version=r.nextVersionIdMarker||'';}
      const seen=new Set<string>();if(items.length>limit)throw new StorageError('UNAVAILABLE');for(const item of items){try{validKey(item.key);validVersionId(item.versionId);}catch{throw new StorageError('UNAVAILABLE','Invalid list result');}const identity=JSON.stringify([item.key,item.versionId]);if(!item.key.startsWith(prefix)||!Number.isSafeInteger(item.size)||item.size<0||seen.has(identity))throw new StorageError('UNAVAILABLE','Invalid list result');seen.add(identity);}
      const next=Buffer.from(JSON.stringify({mode,prefix,key,version,token})).toString('base64url');if(truncated&&(next.length>8192||!items.length||next===input.cursor||(!mode&&!token)||(mode&&(!key||!version||!key.startsWith(prefix)))))throw new StorageError('UNAVAILABLE','Invalid pagination');return {items,cursor:truncated?next:undefined};
    })
  }) as VersionedStorageProvider;
}
